apiVersion: v1
kind: Pod
metadata:
  name: metastore-standalone
  namespace: dev
  labels:
    name: metastore-standalone
spec:
  initContainers:
  - name: download-dependencies
    image: busybox:1.28
    command:
    - /bin/sh
    - -c
    - |
      wget -P /jars https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.2/hadoop-aws-3.2.2.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/aws-java-sdk-bundle-1.11.271.jar
    volumeMounts:
    - name: jar-volume
      mountPath: /jars
  containers:
  - name: hive-metastore
    image: apache/hive:3.1.3
    resources:
      limits:
        memory: 1G
        cpu: "1"
    env:
    - name: SERVICE_NAME
      value: "metastore"
    - name: AWS_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: accessKey

      #value: "eWPnZFJ0aK0WHBEn4DQZ"
    - name: AWS_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: secretKey
      #value: "XyzlHA7iL5JihAmzkoar0GP1gwnTemEj9ojMolUK"
    # - name: AWS_ACCESS_KEY_ID
    #   value: YOUR_AWS_ACCESS_KEY
    # - name: AWS_SECRET_ACCESS_KEY
    #   value: YOUR_AWS_SECRET_KEY
    ports:
    - containerPort: 9083
    command: ["/bin/bash", "-c", "mv /jars/* /opt/hadoop/share/hadoop/common && /opt/hive/bin/schematool -dbType derby -initSchema && exec /opt/hive/bin/hive --skiphadoopversion --skiphbasecp --service metastore --hiveconf fs.s3a.endpoint=your-s3-endpoint"]
    volumeMounts:
    - name: jar-volume
      mountPath: /jars
  volumes:
  - name: jar-volume
    emptyDir: {}