apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: root1234
  user: root

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-metastore
spec:
  selector:
    matchLabels:
      app: mysql-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-metastore
    spec:
      containers:
      - image: mysql:latest
        name: mysql-metastore
        resources:
          limits:
            memory: 1G
            cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_ROOT_HOSTS
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-metastore
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-metastore