apiVersion: batch/v1
kind: CronJob
metadata:
  name: bronze-silver-job
  namespace: dev
spec:
  schedule: "*/5 * * * *"  # Executa a cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          initContainers:
          - name: download-script
            image: curlimages/curl:latest
            command: 
            - /bin/sh
            - -c
            - |
              /bin/sh <<'EOF'
              curl --create-dirs -O --output-dir /mnt/scripts https://raw.githubusercontent.com/Jefsuu/ya-data-project-with-dbt/dev/apps/scripts/bronze_silver_app.py
              EOF
            volumeMounts:
              - name: script-volume
                mountPath: /mnt/scripts
          containers:
          - name: start-bronze-silver-job
            image: python:3.8
            resources:
              limits:
                memory: "512Mi"
                cpu: "500m"
              requests:
                memory: "128Mi"
                cpu: "100m"
            env: 
            - name: BOOTSTRAP_SERVERS
              value: "dev-kafka:9092"
            - name: KAFKA_TOPIC
              value: "minio_bronze_events"
            - name: KAFKA_GROUP_ID
              value: "spark_bronze_silver"
            - name: MYSQL_DATABASE_HOST
              value: "mysql-metastore"
            - name: MYSQL_DATABASE
              value: "topics"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef: 
                  name: "mysql-secret"
                  key: "user"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: "mysql-secret"
                  key: "password"
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secret
                  key: accessKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secret
                  key: secretKey
            command: 
            - /bin/sh
            - -c
            - |
              /bin/sh <<'EOF'
              mkdir /scripts
              cp -R /mnt/scripts/* /scripts
              pip install kafka-python==2.0.2 mysql-connector-python kubernetes==29.0.0 mysql-connector-python==8.3.0
              python /scripts/bronze_silver_app.py
              EOF
            volumeMounts:
              - name: script-volume
                mountPath: /mnt/scripts
          volumes:
            - name: script-volume
              emptyDir: {}
