apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: dev
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes


---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"